function getWeekDate(dayOffset) {
  const now = new Date();
  const day = now.getDay(); // 0=Sun, 1=Mon ... 6=Sat
  const monday = new Date(now);
  const diff = day === 0 ? -6 : 1 - day;
  monday.setDate(now.getDate() + diff);
  monday.setHours(0, 0, 0, 0);
  const target = new Date(monday);
  target.setDate(monday.getDate() + dayOffset);
  return target.toISOString().split('T')[0];
}

export const seedOpgaver = [
  // Monday – Anders, Maria, Peter
  {
    id: 'opgave-1',
    ordrenummer: 'CG-001',
    kundenavn: 'Lars Pedersen',
    kundeKontakt: '+45 21 34 56 78',
    kundeEmail: 'lars.pedersen@gmail.com',
    kundeAdresse: 'Valdemarsgade 12, 1665 København V',
    bil: { mærke: 'VW', model: 'Golf', nummerplade: 'AB 12 345', årstal: 2019, stelnummer: 'WVWZZZ1KZAM012345' },
    opgavetype: 'Forrude udskiftning',
    beskrivelse: 'Forruden er revnet fra bunden og op langs siden. Skal udskiftes hurtigst muligt.',
    lokation: 'Valby',
    dele: 'VW Golf forrude OEM 2019',
    noter: 'Kunden ønsker at blive kontaktet når bilen er klar.',
    tidsestimat: 90,
    status: 'Afsluttet',
    reparatørId: 'rep-1',
    dato: getWeekDate(0),
    starttid: '08:00',
  },
  {
    id: 'opgave-2',
    ordrenummer: 'CG-002',
    kundenavn: 'Sofie Andersen',
    kundeKontakt: '+45 31 45 67 89',
    kundeEmail: 'sofie.andersen@hotmail.com',
    kundeAdresse: 'Nørre Allé 7, 2200 København N',
    bil: { mærke: 'Toyota', model: 'Yaris', nummerplade: 'CD 23 456', årstal: 2021, stelnummer: 'NMTK33BX10R023456' },
    opgavetype: 'Stenslag reparation',
    beskrivelse: 'Lille stenskade i øjenhøjde på forruden. Revnen er ca. 2 cm.',
    lokation: 'Nørrebro',
    dele: 'Reparationsharpiks kit',
    noter: 'Reparation foretrækkes frem for udskiftning.',
    tidsestimat: 30,
    status: 'I gang',
    reparatørId: 'rep-2',
    dato: getWeekDate(0),
    starttid: '09:00',
  },
  {
    id: 'opgave-3',
    ordrenummer: 'CG-003',
    kundenavn: 'Mikkel Sørensen',
    kundeKontakt: '+45 41 56 78 90',
    kundeEmail: 'mikkel.s@email.dk',
    kundeAdresse: 'Amagerbrogade 45, 2300 København S',
    bil: { mærke: 'Ford', model: 'Focus', nummerplade: 'EF 34 567', årstal: 2018, stelnummer: 'WF04XXGCC4KA34567' },
    opgavetype: 'Siderude udskiftning',
    beskrivelse: 'Venstre bagsiderude er smadret. Muligvis indbrud. Kunden har anmeldt det til politiet.',
    lokation: 'Amager',
    dele: 'Ford Focus bagsiderude venstre 2018',
    noter: 'Kunden afleverer bilen kl. 08:00.',
    tidsestimat: 60,
    status: 'Afventer',
    reparatørId: 'rep-3',
    dato: getWeekDate(0),
    starttid: '10:00',
  },

  // Tuesday – Anders, Maria, Peter
  {
    id: 'opgave-4',
    ordrenummer: 'CG-004',
    kundenavn: 'Hanne Møller',
    kundeKontakt: '+45 51 67 89 01',
    kundeEmail: 'hanne.moller@work.dk',
    kundeAdresse: 'Frederiksberg Allé 22, 2000 Frederiksberg',
    bil: { mærke: 'Peugeot', model: '308', nummerplade: 'GH 45 678', årstal: 2020, stelnummer: 'VF3LBHZUUJL045678' },
    opgavetype: 'Forrude udskiftning',
    beskrivelse: 'Forruden har fået et kraftigt slag fra en lastbil på motorvejen. Akut udskiftning nødvendig.',
    lokation: 'Frederiksberg',
    dele: 'Peugeot 308 forrude OEM 2020',
    noter: 'Akut sag – kunden har ingen erstatningsbil.',
    tidsestimat: 90,
    status: 'Afventer',
    reparatørId: 'rep-1',
    dato: getWeekDate(1),
    starttid: '08:30',
  },
  {
    id: 'opgave-5',
    ordrenummer: 'CG-005',
    kundenavn: 'Thomas Christensen',
    kundeKontakt: '+45 61 78 90 12',
    kundeEmail: 'thomas.c@firma.dk',
    kundeAdresse: 'Østerbrogade 88, 2100 København Ø',
    bil: { mærke: 'BMW', model: 'X5', nummerplade: 'IJ 56 789', årstal: 2022, stelnummer: '5UXCR6C59KLL56789' },
    opgavetype: 'Stenslag reparation',
    beskrivelse: 'To stenskader på forruden, begge under 2 cm. Reparation bør kunne klares inden for 45 minutter.',
    lokation: 'Østerbro',
    dele: 'Reparationsharpiks kit premium',
    noter: 'Firmabil – faktura til Christensen Holding ApS.',
    tidsestimat: 45,
    status: 'Afventer',
    reparatørId: 'rep-2',
    dato: getWeekDate(1),
    starttid: '11:00',
  },
  {
    id: 'opgave-6',
    ordrenummer: 'CG-006',
    kundenavn: 'Birgitte Hansen',
    kundeKontakt: '+45 71 89 01 23',
    kundeEmail: 'birgitte.h@privat.dk',
    kundeAdresse: 'Vanløse Allé 15, 2720 Vanløse',
    bil: { mærke: 'Audi', model: 'A4', nummerplade: 'KL 67 890', årstal: 2017, stelnummer: 'WAUZZZ8K7HA067890' },
    opgavetype: 'Bagrude udskiftning',
    beskrivelse: 'Bagruden er slået af vandaler natten til i dag. Kunden er meget frustreret.',
    lokation: 'Vanløse',
    dele: 'Audi A4 bagrude med varmelegeme 2017',
    noter: 'Forsikringssag – forsikringsnummer: TDK-2024-8821.',
    tidsestimat: 120,
    status: 'Afventer',
    reparatørId: 'rep-3',
    dato: getWeekDate(1),
    starttid: '09:00',
  },

  // Wednesday – Anders, Maria, Peter
  {
    id: 'opgave-7',
    ordrenummer: 'CG-007',
    kundenavn: 'Jesper Rasmussen',
    kundeKontakt: '+45 81 90 12 34',
    kundeEmail: 'jesper.r@email.dk',
    kundeAdresse: 'Brønshøjvej 33, 2700 Brønshøj',
    bil: { mærke: 'Skoda', model: 'Octavia', nummerplade: 'MN 78 901', årstal: 2016, stelnummer: 'TMBHE61Z1H7078901' },
    opgavetype: 'Forrude udskiftning',
    beskrivelse: 'Forruden er revnet i bunden og revnen breder sig. Skal udskiftes hurtigst muligt.',
    lokation: 'Brønshøj',
    dele: 'Skoda Octavia forrude OEM 2016',
    noter: 'Kunden afleverer bilen om morgenen og henter om eftermiddagen.',
    tidsestimat: 90,
    status: 'Afventer',
    reparatørId: 'rep-1',
    dato: getWeekDate(2),
    starttid: '08:00',
  },
  {
    id: 'opgave-8',
    ordrenummer: 'CG-008',
    kundenavn: 'Camilla Nielsen',
    kundeKontakt: '+45 91 01 23 45',
    kundeEmail: 'camilla.nielsen@gmail.com',
    kundeAdresse: 'Hvidovrevej 67, 2650 Hvidovre',
    bil: { mærke: 'Mercedes', model: 'C-klasse', nummerplade: 'OP 89 012', årstal: 2023, stelnummer: 'WDD2050231R089012' },
    opgavetype: 'Siderude udskiftning',
    beskrivelse: 'Forreste højre siderude er knust. Kunden er forsikret og ønsker original rude.',
    lokation: 'Hvidovre',
    dele: 'Mercedes C-klasse siderude højre OEM 2023',
    noter: 'OEM rude kræves af forsikringen.',
    tidsestimat: 60,
    status: 'Afventer',
    reparatørId: 'rep-2',
    dato: getWeekDate(2),
    starttid: '10:00',
  },
  {
    id: 'opgave-9',
    ordrenummer: 'CG-009',
    kundenavn: 'Rasmus Lund',
    kundeKontakt: '+45 20 11 22 33',
    kundeEmail: 'rasmus.lund@work.dk',
    kundeAdresse: 'Lyngby Hovedgade 12, 2800 Kongens Lyngby',
    bil: { mærke: 'Volvo', model: 'V60', nummerplade: 'QR 90 123', årstal: 2021, stelnummer: 'YV1FW8GK0M2090123' },
    opgavetype: 'Spejl udskiftning',
    beskrivelse: 'Venstre sidespejl er knækket af. Glas og hus skal udskiftes.',
    lokation: 'Lyngby',
    dele: 'Volvo V60 spejl venstre komplet 2021',
    noter: 'Kunden ønsker originalt Volvo-spejl.',
    tidsestimat: 45,
    status: 'Afventer',
    reparatørId: 'rep-3',
    dato: getWeekDate(2),
    starttid: '13:00',
  },

  // Thursday – Anders, Maria, Peter
  {
    id: 'opgave-10',
    ordrenummer: 'CG-010',
    kundenavn: 'Mette Jacobsen',
    kundeKontakt: '+45 29 33 44 55',
    kundeEmail: 'mette.j@privat.dk',
    kundeAdresse: 'Glostrup Stationsvej 8, 2600 Glostrup',
    bil: { mærke: 'Hyundai', model: 'i30', nummerplade: 'ST 01 234', årstal: 2020, stelnummer: 'KMHD35LH0LU101234' },
    opgavetype: 'Forrude udskiftning',
    beskrivelse: 'Stor revne fra stenskade der har spredt sig. Forruden er ikke til at redde.',
    lokation: 'Glostrup',
    dele: 'Hyundai i30 forrude OEM 2020',
    noter: 'Kunden venter på værkstedet mens arbejdet udføres.',
    tidsestimat: 90,
    status: 'Afventer',
    reparatørId: 'rep-1',
    dato: getWeekDate(3),
    starttid: '09:00',
  },
  {
    id: 'opgave-11',
    ordrenummer: 'CG-011',
    kundenavn: 'Nikolaj Berg',
    kundeKontakt: '+45 30 44 55 66',
    kundeEmail: 'nikolaj.berg@firma.dk',
    kundeAdresse: 'Nørre Farimagsgade 55, 1364 København K',
    bil: { mærke: 'Honda', model: 'Civic', nummerplade: 'UV 12 345', årstal: 2019, stelnummer: 'SHHFK9760KU012345' },
    opgavetype: 'Stenslag reparation',
    beskrivelse: 'Enkelt stenskade ca. 1 cm i kørerens synsfelt. Skal repareres inden næste syn.',
    lokation: 'Østerbro',
    dele: 'Reparationsharpiks kit',
    noter: 'Syn om 3 uger – reparation skal bekræftes skriftligt.',
    tidsestimat: 30,
    status: 'Afventer',
    reparatørId: 'rep-2',
    dato: getWeekDate(3),
    starttid: '11:30',
  },
  {
    id: 'opgave-12',
    ordrenummer: 'CG-012',
    kundenavn: 'Anne-Marie Petersen',
    kundeKontakt: '+45 40 55 66 77',
    kundeEmail: 'am.petersen@hotmail.dk',
    kundeAdresse: 'Frederikssundsvej 102, 2400 København NV',
    bil: { mærke: 'Seat', model: 'Leon', nummerplade: 'WX 23 456', årstal: 2018, stelnummer: 'VSSZZZ5FZJR023456' },
    opgavetype: 'Bagrude udskiftning',
    beskrivelse: 'Bagruden har en revne på tværs. Opvarmningselement virker ikke mere.',
    lokation: 'Nørrebro',
    dele: 'Seat Leon bagrude med varmelegeme 2018',
    noter: 'Sikre at varmelegemet testes efter montering.',
    tidsestimat: 60,
    status: 'Afventer',
    reparatørId: 'rep-3',
    dato: getWeekDate(3),
    starttid: '08:30',
  },

  // Friday – Anders, Maria, Peter
  {
    id: 'opgave-13',
    ordrenummer: 'CG-013',
    kundenavn: 'Klaus Vestergaard',
    kundeKontakt: '+45 50 66 77 88',
    kundeEmail: 'k.vestergaard@gmail.com',
    kundeAdresse: 'Sundby Allé 3, 2300 København S',
    bil: { mærke: 'VW', model: 'Golf', nummerplade: 'YZ 34 567', årstal: 2017, stelnummer: 'WVWZZZ1KZH7034567' },
    opgavetype: 'Siderude udskiftning',
    beskrivelse: 'Bageste venstre siderude er smadret. Indbrud i bilen natten til fredag.',
    lokation: 'Amager',
    dele: 'VW Golf bagsiderude venstre 2017',
    noter: 'Politirapport vedlagt. Forsikringsformular udfyldes på stedet.',
    tidsestimat: 60,
    status: 'Afventer',
    reparatørId: 'rep-1',
    dato: getWeekDate(4),
    starttid: '10:00',
  },
  {
    id: 'opgave-14',
    ordrenummer: 'CG-014',
    kundenavn: 'Dorte Skovgaard',
    kundeKontakt: '+45 60 77 88 99',
    kundeEmail: 'dorte.s@email.dk',
    kundeAdresse: 'Smallegade 28, 2000 Frederiksberg',
    bil: { mærke: 'Peugeot', model: '308', nummerplade: 'AA 45 678', årstal: 2022, stelnummer: 'VF3LBHZUUKL045678' },
    opgavetype: 'Forrude udskiftning',
    beskrivelse: 'Forruden er revnet fra øverste hjørne og ned. Revnen er ca. 30 cm.',
    lokation: 'Frederiksberg',
    dele: 'Peugeot 308 forrude OEM 2022',
    noter: 'Kunden ønsker besked 30 min før bilen er klar.',
    tidsestimat: 90,
    status: 'Afventer',
    reparatørId: 'rep-2',
    dato: getWeekDate(4),
    starttid: '08:00',
  },
  {
    id: 'opgave-15',
    ordrenummer: 'CG-015',
    kundenavn: 'Simon Dalgaard',
    kundeKontakt: '+45 70 88 99 00',
    kundeEmail: 'simon.d@firma.dk',
    kundeAdresse: 'Lyngby Storcenter 7, 2800 Kongens Lyngby',
    bil: { mærke: 'BMW', model: 'X5', nummerplade: 'BB 56 789', årstal: 2023, stelnummer: '5UXCR6C50PLL56789' },
    opgavetype: 'Spejl udskiftning',
    beskrivelse: 'Højre sidespejl er beskadiget efter parkeringshændelse. Glas knust.',
    lokation: 'Lyngby',
    dele: 'BMW X5 spejl højre glas OEM 2023',
    noter: 'Kun glasset udskiftes – huset er intakt.',
    tidsestimat: 45,
    status: 'Afventer',
    reparatørId: 'rep-3',
    dato: getWeekDate(4),
    starttid: '13:00',
  },
];

export const seedPauser = [];
